GET http://localhost:3000/api/v1/employees

###

GET http://localhost:3000/api/v1/employees?ReportsTo=1&Title=IT%20Manager

###

GET http://localhost:3000/api/v1/employees?title=Sales%20Support%20Agent

###

GET http://localhost:3000/api/v1/employees?Title=Sales%20Support%20Agent&City=Calgary&FirstName=Jane

###

GET http://localhost:3000/api/v1/employees?API_KEY=maria

###

GET http://localhost:3000/api/v1/employees?Title=Sales%20Support%20Agent&API_KEY=maria

###

GET http://localhost:3000/api/v1/employees?API_KEY=kerim

###

GET http://localhost:3000/api/v1/employees/1

###

GET http://localhost:3000/api/v1/artists

###

GET http://localhost:3000/api/v1/artists/1

###

POST http://localhost:3000/api/v1/employees HTTP/1.1
content-type: application/json

{
  "FirstName": "John",
  "LastName": "Smith"
}

###

PUT http://localhost:3000/api/v1/employees/9 HTTP/1.1
content-type: application/json

{
  "FirstName": "Alice"
}

###

DELETE http://localhost:3000/api/v1/employees/9 HTTP/1.1

###


GET http://localhost:3000/api/v1/users HTTP/1.1
###

POST http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json

{
  "Email": "johndoe@email.com",
  "Password": "Password",
  "GivenName": "John Doe",
  "Role": "User"
}

###

POST http://localhost:3000/api/v1/users/register HTTP/1.1
content-type: application/json

{
  "Email": "janedoe@email.com",
  "Password": "Password"
}

###

POST http://localhost:3000/api/v1/users/login HTTP/1.1
content-type: application/json

{
  "Email": "janedoe@email.com",
  "Password": "Password"
}

###

GET http://localhost:3000/api/v1/users/logout HTTP/1.1
content-type: application/json

{
  "Email": "janedoe@email.com"
}


###

